### ISSUE TITLE
'GSM_PIN' was not declared

### ISSUE THREAD

**Issue by Forairaaaaa** [erazor83/nb_dtu_reset_issue#1]
https://github.com/erazor83/nb_dtu_reset_issue/blob/c2ed7d21a6e307c9050dd5c86d15aa94f095e196/src/main.ino#L160

Hi, I'm trying to compile this code with pio, but I didn't find the define of `GSM_PIN`

https://github.com/erazor83/nb_dtu_reset_issue/blob/c2ed7d21a6e307c9050dd5c86d15aa94f095e196/src/main.ino#L156

And about this comment, do you mean adding this `modem.factoryDefault()` causing the issue?

Thanks

**Comment by erazor83** [comment]
Hi.

You can check out the newest code or just remove the PIN part. I've used a Card without PIN and that does not influence my issue.

And yes, factoryDefault seems to be the problem. The module responses correctly after that line and got stuck for the modem.waitForNetwork check for me. I've unplugged it after about 15 minutes while it runs the modem.waitForNetwork loop. 
After that it never answered any AT anymore.

**Comment by erazor83** [comment]
added a define check for GSM_PIN.

Moved AT issue to https://github.com/erazor83/nb_dtu_reset_issue/issues/2
